# .github/workflows/docker-image.yml
name: Docker Image CI
# when Push or PR trigger this pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Runs in environement + steps for pipeline using github actions
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
# github plugin helps us to build image
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
# Login github action (authentication)
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io   # u can change to another registry (Github Container Registry)
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
# Push image in github
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . # where Dockerfile exist to build
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/getting-started:latest
          ghcr.io/${{ github.repository_owner }}/getting-started:${{ github.sha }}
# best pracice use hash of image to define version 
# u can other testing | Quality assurance